version: '2'
services:
    project:
        image: apache2:php5
        restart: always
        container_name: nome-projeto
        environment:
            - VIRTUAL_HOST=domain.com
        ports:
            - 8080:80
        volumes:
            - ${PWD}:/var/www/html
            - /etc/hosts:/etc/hosts
        extra_hosts:
            - "pgproducao:169.57.148.35"
            - "pgdesenvolvimento:169.57.148.35"
            - "dbsms:169.57.148.35"
            - "dbsia:169.57.148.35"
            - "dbvoz:10.150.71.238"
            - "dbmongo:10.150.71.238"
            - "dbchat:169.57.148.58"
            - "dbemail:169.57.148.38"
            - "dbdigital:169.57.148.38"
