version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EyKeNoI0VRjI
    ports:
      - 3306:3306
    networks:
      local_mysql:

networks:
  local_mysql:
