version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=EyKeNoI0VRjI
    ports:
      - '5432:5432'
    networks:
      local_postgres:

networks:
  local_postgres:
